<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9586cdfa-d035-4c16-9094-6466f8f56f14</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lodestone.Application\Lodestone.Application.csproj" />
    <ProjectReference Include="..\Lodestone.Infrastructure\Lodestone.Infrastructure.csproj" />
    <ProjectReference Include="..\Lodestone.ML\Lodestone.ML.csproj" />
    <ProjectReference Include="..\Lodestone.Jobs\Lodestone.Jobs.csproj" />
    <ProjectReference Include="..\Lodestone.Reporting\Lodestone.Reporting.csproj" />
    <ProjectReference Include="..\Lodestone.Domain\Lodestone.Domain.csproj" />
    <ProjectReference Include="..\Lodestone.Shared\Lodestone.Shared.csproj" />
  </ItemGroup>

</Project>
